/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTriple */

#ifndef _Included_NativeTriple
#define _Included_NativeTriple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTriple
 * Method:    allocRandomTriple
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeTriple_allocRandomTriple
  (JNIEnv *, jclass);

/*
 * Class:     NativeTriple
 * Method:    freeTriple
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_NativeTriple_freeTriple
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
